### ISSUE TITLE
no nameservers

### ISSUE THREAD

**Issue by jc2it** [42wim/dt#3]
In using the project I receive the following message for all attempts.
"no nameservers found for <domain>"

Is there a setting to point the tool to a particular DNS?

**Comment by 42wim** [comment]
If you do ```dt google.com``` you also get this message ?
It tries to connect to 8.8.8.8 if you can't reach that host, it can't resolve and will fail.
Specifying a specific resolver and/or using directly root-servers will be available soon

**Comment by jc2it** [comment]
Found firewall restriction on DNS usage. Changed setting to allow alternate DNS server. dt now functions as expected.
