### ISSUE TITLE
Feature Request: Output to txt

### ISSUE THREAD

**Issue by BatchHeader** [42wim/dt#4]
It would be a great feature to be able to output to a txt file to keep a snapshot of the domain.
I have tried `dt -scan example.com > example.com.txt` but ended up with full cli output of waiting animation and "waiting for scan":
`⠋   ⠙   ⠹   ⠸   ⠼   ⠴   ⠦ `

**Comment by 42wim** [comment]
Ok, This is fixed now in master. 
The spinner displays to stderr.
You'll have to rebuild from master for now, this fix is too small to warrant a new version.

**Comment by BatchHeader** [comment]
@42wim That's excellent. I'll try it out.
