### ISSUE TITLE
SOA serial in unixtime should not be a warning

### ISSUE THREAD

**Issue by aabdnn** [42wim/dt#5]
dt issues a warning for any serial number not in YYYYMMDDNN format. As an experienced DNS operator, I disagree with this opinion. The serial number can be in any format that allows the operator to operate the zone effectively. YYYYMMDDNN is just a recommendation, and is mainly for hand-maintained zones that don't change often. For anything else, unixtime, or a simple increment, is more useful, and it should not be flagged as a warning. I think that the check for the format of the serial format should be dropped altogether. Emitting a false warning is misleading.

**Comment by 42wim** [comment]
Thanks for the feedback.
I agree, I'll remove the warning.

**Comment by aabdnn** [comment]
Thanks Wim! And thank you for creating such a nice diagnostic tool :)
