### ISSUE TITLE
debian packaging: resolve fork

### ISSUE THREAD

**Issue by anarcat** [42wim/dt#8]
Hi,

I'm looking at packaging this tool for Debian. One of the problems I'm facing is that one of your dependencies is a fork of an upstream package (ipisp) without any official releases (https://github.com/ammario/ipisp/issues/16).

Would you consider switching to the official upstream so that we don't have to track two different source packages in Debian? Is there any reason why you need a fork of that code?

Thank you so much for your hard work!

**Comment by 42wim** [comment]
It seems that issue is now fixed upstream.
So I'm going to update my vendored dependencies and release a v0.0.10 that you could package.

**Comment by anarcat** [comment]
awesome, thanks

**Comment by 42wim** [comment]
There you go, going to close this.
If there a any other issues, feel free to ping

**Comment by anarcat** [comment]
fixed in https://github.com/42wim/dt/commit/07db470c823b9c2c37a0a53d0fad597f0f2eac1b, FTR thanks!
